In [ ]:
%load_ext autoreload
%autoreload 2

# `Bloque Cero`

## Tema: Ideas básicas sobre Python y algunos paquetes fundamentales (part4)


## Tópicos
- Módulos, paquetes y namespaces

- [Numpy](https://numpy.org)

## Módulos, paquetes y namespaces


### Creando módulos y paquetes


>> Módulos

En Python, cada archivo con extensión `.py` se considera un módulo. Un módulo puede contener variables, funciones, clases e incluso código ejecutable.

La principal ventaja de los módulos es que permiten organizar el código de forma más clara y reutilizable. En lugar de tener todo el código en un solo archivo, podemos dividirlo en varios archivos más pequeños y enfocados, lo que facilita su mantenimiento y comprensión.

>> Paquetes

Cuando agrupamos varios módulos en una carpeta, y esa carpeta incluye un archivo especial llamado __init__.py, estamos creando un paquete (package). Esto nos permite organizar el código en una estructura jerárquica, ideal para proyectos grandes o complejos.

Un paquete no es más que una carpeta que contiene archivos .py, es decir, módulos. Para que Python lo reconozca como un paquete, tradicionalmente debía contener un archivo llamado __init__.py. Aunque en versiones modernas de Python este archivo no siempre es obligatorio, sigue siendo una buena práctica incluirlo.

El archivo __init__.py puede estar vacío; su presencia simplemente le indica a Python que la carpeta debe tratarse como un paquete, y no como una carpeta común. También se puede usar para inicializar el paquete o definir qué elementos estarán disponibles al importar el paquete.


Los paquetes, a la vez, también pueden contener otros sub-paquetes:

¿Qué se pone en `__init__.py`?

Como mencionamos antes, el archivo `__init__.py` puede estar completamente vacío. Su función principal es indicarle a Python que una carpeta debe tratarse como un paquete.

Sin embargo, es común utilizar `__init__.py` para realizar configuraciones iniciales o exponer ciertos objetos, funciones o clases al nivel del paquete, facilitando su uso desde el exterior.

Esto resulta útil si quieres que al importar el paquete, se acceda directamente a ciertos elementos sin necesidad de navegar por cada módulo individual.


podemos utilizar `__init__.py` para que las funciones, clases, etc. deseadas estén disponible al nivel de paquete llamándolos (`importandolos`) en este archivo, por ejemplo, si ponemos en el `__init__.py` principal

- `from .presentacion import hola`

ya no tendríamos que llamarlo en el código como:

- `from matematicas.presentacion import hola`

sinó solo usaríamos:
- `from matematicas import hola`

In [1]:
import matematicas as mat

ModuleNotFoundError: No module named 'matematicas'

In [4]:
mat.hola()

Hola mundo


In [1]:
from matematicas import hola

hola()

Hola mundo


En nuestro paquete intencionalmente dejamos vacio el `__init__.py` del subpaquete multiplicacion_division. Veamos que ahora no aplica lo anterior

In [ ]:
# from matematicas.multiplicacion_division import multiplicacion
# from matematicas.multiplicacion_division.multiplicacionF import multiplicacion

multiplicacion(2, 1, 3)

6

>> La variable especial `__all__`

Otro elemento que puede incluirse en `__init__.py` es la variable especial `__all__`. La cual es una lista de cadenas de texto con los nombres de los objetos que deseas exponer públicamente al hacer una importación global. Esta variable define qué símbolos (funciones, clases, variables, etc.) se importan cuando se usa la instrucción `import *`. Por ejemplo en el `__init__.py` principal solo se puse que se cargara la función `hola`. Vean que ocurre


In [1]:
from matematicas import *
# adios()
hola()

Hola mundo


IMPORTANTE: la exigencia de que aparezca `__init__.py` dentro de cada folder para que pueda considerarse un paquete puede ser omitida en `Python 3`. Para esta versión si tenemos esta estructura

Notar que no existe el archivo `__init__.py`. Sin embargo, siempre y cuando la carpeta paquete forme parte del PYTHONPATH (o sea, que python puede importarla), `ninguno de los siguientes import dará error bajo Python 3` (aunque sí lo darían en `Python 2` por no existir `__init__.py` en la carpeta paquete).

- `import paquete.modulo1` permitirá dentro del código hacer uso de cualquier símbolo definido en **paquete/modulo1.py**.

- `from paquete import modulo1` es análogo al anterior.

- `import paquete` no dará error, pero no sirve de nada ya que este lo que haría es ejecutar `paquete/__init__.py` pero en este caso no existe. Daría un error si intentará dentro del programa acceder a por ejemplo `paquete/modulo1.py` pq no lo he cargado.

Ahora bien, si añadiéramos un `__init__.py`, entonces `import paquete` se ejecutaría y cargaría las ordenes dadas en `__init__.py`. Si este estuviera vacio pasaría lo mismo que como sino estuviera.

In [4]:
# mover __init__.py principal para fuera y hacer test
# from matematicas import presentacion as pr
from matematicas.presentacion import hola

hola()

Hola mundo


>> Últimos comentarios: 

**¿Qué pasa si nuestro paquete no está en el directorio raíz?**

Cuando desarrollamos un paquete, puede que no esté ubicado directamente en el directorio desde donde ejecutamos nuestros scripts, o que queramos reutilizarlo en varios proyectos. En estos casos, Python no lo encontrará automáticamente a menos que:

- esté dentro del PYTHONPATH, o
- esté instalado como un paquete en el entorno de Python.

⸻

**¿Cómo instalamos nuestro propio paquete?**

Para poder usar nuestro paquete desde cualquier lugar, lo ideal es crear un paquete distribuible (también llamado “distribución”) e instalarlo en el entorno de Python.

Supongamos esta estructura de proyecto:

Ahora creamos un fichero `setup.py` fuera de la raíz, indicando la estructura y ciertos datos. Por ejemplo:

In [ ]:
from setuptools import setup

setup(
    name = "paqMatematica",
    version = "0.1",
    description = "Esto es un ejemplo",
    author = "Armando A.",
    author_email = "arestrada@fisica.ugto.mx",
    url = "",
    install_requires = [], # añade cualquier paquete adicional que debe ser
                         # instalado una vez que se instale el paquete
    keywords = ['python', 'primer paquete'],
    packages = ['matematicas', 'matematicas.suma_resta', 'matematicas.multiplicacion_division'],  # estructura
    scripts = []
)

Una versión más automática sería usando:

💡 find_packages() detecta automáticamente subcarpetas que contengan "__init__.py".

In [ ]:
# setup.py
from setuptools import setup, find_packages

setup(
    name="mimodulo",
    version="0.1",
    packages=find_packages(),
    install_requires=[],
)

**Crear y distribuir un paquete con setup.py**

Una vez que tenemos nuestro archivo `setup.py` correctamente configurado, podemos generar un paquete distribuible (es decir, un archivo comprimido que contiene todo lo necesario para instalar nuestro módulo).

✅ Compilar el paquete

Desde el directorio donde está ubicado `setup.py`, ejecutamos en la terminal:

Este comando crea una carpeta llamada dist/ y dentro de ella aparecerá un archivo comprimido, como:

Este archivo es el distribuible que puedes compartir o instalar en otros entornos.

✅ Instalar el paquete localmente con pip

Para instalarlo, simplemente usamos pip apuntando al archivo generado:

Si has generado un .zip, también puedes instalarlo así:

Una vez instalado, podrás importar tu módulo desde cualquier lugar. Por ejemplo:

🧼 Desinstalar el paquete

Si deseas eliminarlo de tu entorno:

📝 Nota Importantes

- Si estás distribuyendo un proyecto más moderno, se ha de usar `pyproject.toml` en lugar de `setup.py`, ya que es la nueva forma recomendada por la comunidad Python.

Veamos el mismo ejemplo:

🧰 Crear un paquete usando pyproject.toml

Supongamos que tu proyecto tiene esta estructura:

📄 Contenido de pyproject.toml

In [ ]:
[project]
name = "matematicas"
version = "0.1.0"
description = "Un paquete de ejemplo con operaciones matemáticas"
authors = [
  {name="Armando A.", email="arestrada@fisica.ugto.mx"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.7"
keywords = ["matemáticas", "educación", "aritmética", "python"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Education",
  "Topic :: Education",
]
dependencies = [
  "numpy>=1.21"
]

[project.urls]
Homepage = "https://github.com/juanperez/matematicas"
Documentation = "https://juanperez.github.io/matematicas"
Source = "https://github.com/juanperez/matematicas"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

🎯 Notar que este archivo reemplaza a setup.py.

✅ Generar el paquete distribuible

Una vez tengas el `pyproject.toml` creado, necesitas instalar las herramientas para construirlo:

Luego ejecuta:

Esto creará dos archivos en una nueva carpeta dist/:

📦 Instalar el paquete localmente

Instálalo con pip así:

## Importando módulos

### Importando módulos enteros

En Python, el contenido de un módulo (es decir, las funciones, clases y variables definidas en él) puede ser reutilizado en otros módulos. Para hacerlo, debemos importar explícitamente aquellos módulos que queremos usar.

🔑 Sintaxis

La instrucción básica para importar es:

Si el módulo forma parte de un paquete o subpaquete, se indica su ruta jerárquica separada por puntos (.), omitiendo la extensión .py.


✅ Nota: Esto no importa directamente las funciones o clases definidas en el módulo, sino el módulo como objeto. Para usar sus contenidos, deberás referenciar su nombre completo:

### Alias

Es posible también, abreviar los namespaces mediante un **alias**. Para ello, durante la
importación, se asigna la palabra clave as seguida del alias con el cuál nos referiremos
en el futuro a ese namespace importado.

Ejemplo:

IMPORTANTE

Luego, para acceder a cualquier elemento de los módulos importados, el namespace
utilizado será el alias indicado durante la importación. 

Ejemplo:

In [ ]:
#import numpy
import numpy as np

#numpy.sqrt(5)
np.sqrt(5)  # notar el np delante para indicar el módulo

### Importar módulos particulares

En Python, es posible también, importar de un módulo **solo** los elementos que se desee
utilizar. Para ello se utiliza la instrucción `from` seguida del namespace, más la instrucción
`import` seguida del elemento que se desee importar:

In [ ]:
# ejemplo 1
from scipy.interpolate import interp1d, Rbf, InterpolatedUnivariateSpline

In [ ]:
# ejemplo 2
from numpy import sqrt as sq

In [ ]:
sq(5)

De forma alternativa (**pero muy poco recomendada**), es importar todos los elementos de un módulo definidos en `__all__`, **sin utilizar su namespace pero tampoco alias**. Es decir, que todos los elementos importados **se accederá con su nombre original**:

In [ ]:
# ejemplo

from numpy import *

sqrt(5), sin(4)

El detalle de hacerlo así, es que si se importan dos paquetes que tengan un módulo con el mismo nombre el último que se importe será el que se usará.

Ejemplo:

In [ ]:
from math import *
from numpy import *

In [ ]:
# verifiquen 
sqrt(5)

In [ ]:
# lo cool de numpy
a = [1, 2, 3]

sqrt(a)

📌 Buenas prácticas. PEP 8: Importación

- La importación de módulos debe realizarse al comienzo del documento, en orden alfabético de paquetes y módulos.
- Primero deben importarse los módulos propios de Python.
- Luego, los módulos de terceros y finalmente, los módulos propios de la aplicación.
- Entre cada bloque de imports, debe dejarse una línea en blanco

# Trabajo científico en Python

El análisis de datos básico en Python se apoya en cuatro bibliotecas fundamentales, que se complementan entre sí para cubrir todo el flujo de trabajo científico:


|Biblioteca Función| principal|
|----------|------------|
|NumPy | Manejo eficiente de arreglos (arrays)|
|SciPy |Herramientas para cálculo científico|
|Pandas |Manipulación de datos estructurados (DataFrames)|
|Matplotlib |Visualización y gráficos|


📦 Instalación de las bibliotecas

Estas bibliotecas no forman parte de la biblioteca estándar de Python, por lo que necesitamos instalarlas previamente. Ya que usamos el entorno Conda, recomendamos instalar cada paquete desde canales confiables:

🔄 Importante:
Anaconda ya incluye muchas de estas bibliotecas por defecto. Solo es necesario instalar o actualizar si tu entorno no tiene la versión adecuada.

❗ Si no usas Anaconda…

Si no estás trabajando con Anaconda, puedes usar otro gestor de entornos, como `Pipenv`, para crear un entorno virtual y luego instalar los paquetes con:

Cálculo numérico con Numpy
==========================

Aunque Python tiene varios tipos de datos estructurados, en la práctica no son nada adecuados para cálculo numérico. Veamos un ejemplo de un cálculo numérico básico empleando listas:

In [1]:
import numpy as np

In [ ]:
lista = list(range(5))  # Lista de numeros de 0 a 4
print(lista)

print()
print(lista*3)

print()

print(lista*2.5)

[0, 1, 2, 3, 4]

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]



En el ejemplo anterior vemos cómo al multiplicar una lista por un número entero, el resultado es concatenar la lista original tantas veces como indica el número, en lugar de multiplicar cada uno de sus elementos por este número, que es lo a veces cabría esperar. Es más, al multiplicarlo por un número no entero da un error, al no poder crear una fracción de una lista. Si quisiéramos hacer esto, se podría resolver iterando cada uno de los elementos de la lista con un bucle `for`, por ejemplo:

In [ ]:
print(lista)
lista_nueva = [i*2.5 for i in lista]  # recordar como poner un ciclo for en una linea
print(lista_nueva)

In [ ]:
# alternativa
list(map(lambda x: x*2.5, lista))

estas técnica suelen ser ineficientes y lenta (en versiones viejas de `Python` ya han mejorado), sobre todo cuando queremos evaluar funciones, polinomios o cualquier otra operación matemática que aparece en cualquier problema científico.

Cuando realmente queremos hacer cálculos con listas de números, debemos usar los objetos tipo `¡¡arrays!!` definidos en Numpy.


Veamos un ejemplo

In [5]:
test_list = list(range(1001))

%timeit sum(test_list)  # el tiempo que requiere la mencionada operación

4.29 µs ± 6.22 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
test_array = np.arange(1001)

%timeit np.sum(test_array)

1.75 µs ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Las nuevas versiones de `Python` han mejorado sustancialmente la eficiencia en estos tiempos de evalución, sin embargo, las versatilidad de los `array` hace muy atractivo el uso de `numpy`.

Como se señaló, el módulo `numpy` nos da acceso a los arrays, pero no solo a eso, también a una gran cantidad de métodos y funciones aplicables a los mismos. Naturalmente, `numpy` incluye funciones matemáticas básicas similares al módulo `math`, las completa con otras más elaboradas y además **incluye algunas utilidades de números aleatorios, ajuste lineal de funciones y muchas otras**.

Para trabajar con `numpy` y los arrays, importamos el módulos de alguna de las siguientes maneras:

### Importante 

- Si cargamos el módulo solamente, accederemos a las funciones como `numpy.array()` o `np.array()`, según cómo importemos el módulo. 
- Si en lugar de eso importamos todas las funciones, accederemos a ellas directamente (e.g. `array()`). 

Un array se puede crear explícitamente o a partir de una lista de la forma siguiente:

In [7]:
x = np.array([2.0, 4.6, 9.3, 1.2])      # Creacion de un array directamente

notas = [9.8, 7.8, 9.9, 8.4, 6.7]   # Crear un lista
notas2 = np.array(notas) 

print(notas2)
print(notas)
notas2

[9.8 7.8 9.9 8.4 6.7]
[9.8, 7.8, 9.9, 8.4, 6.7]


array([9.8, 7.8, 9.9, 8.4, 6.7])

Lo primero que notaremos al imprimir un `array` por pantalla es que a diferencia de las listas sus elementos no están separados por comas.

Podemos consultar el tipo de la variable:

In [8]:
print(type(notas2))

<class 'numpy.ndarray'>


Este array formado a partir de una lista se considera un array de una dimensión, también conocido como vector.

Podemos consultar la dimensión y forma de un array con sus propiedades `ndim` y `shape`:

In [9]:
len(notas2), notas2.ndim, notas2.shape

(5, 1, (5,))

Notar como el tercer método nos devolverá una tupla `(5,)`. El segundo método hace referencia a que nuestro array tiene 5 elementos en la primera dimensión, que es la de la anchura, lo cual al ser de 1D, coincide con lo arrojado por `len`.

Ahora bien, si nosotros definimos un array a partir de una lista anidada formada por dos sublistas tendremos:

In [ ]:
array = np.array(
[
    [1, 2, 3, 4., 5],
    [6, 7, 8, 9, 10]
])

print(array)
print(array.ndim)
print(array.shape)

[['1' '2' '3' '4.' '5']
 ['6' '7' '8' '9' '10']]
2
(2, 5)


Veremos algo interesante, y es que el array se muestra como una tabla de **2 filas con 5 columnas**, números que precisamente concuerdan con la forma **(2, 5)**.

Estas estructuras formadas por filas y columnas parecidas a una tabla tienen dos dimensiones, anchura y altura (por eso nos dice que tiene 2 dimensiones). También se conocen como **vectores multidimensionales, vectores 2D o matrices**.

Para conocer el tipo de dato que contiene el array podemos usar `dtype`. IMPORTANTE: un array solo puede contener un tipo de datos.

In [10]:
print(array.dtype)

print()
array = np.array(["Hola", "que", "tal"])
print(array.dtype)

<U4

<U4


Pero en este caso nos indica un tipo extraño llamado **<U4**. Según la documentación de `numpy` esto hace referencia a que el array es de tipo **Unicode**, es decir, es un array de texto.

Esto sucede de igual forma si mezclamos números y textos:

In [7]:
array = np.array([1234, "Hola", 3.1415])
print(array.dtype)

<U32


Ahora nos dice que el tipo es **<U#** y si mostramos su contenido veremos que todo son cadenas de texto:

In [ ]:
print(array)

### Existen métodos para crear arrays automáticamente:

In [ ]:
# Ejemplos

#lista_ceros = np.zeros(10)           # Array de 10 ceros (floats)
lista_ceros = np.zeros([3,3])                    # matriz 3x3 de ceros
print(lista_ceros)

#lista_unos = np.ones(10)             # Array de 10 unos (floats)
lista_unos =  np.ones([3,3])                     # matriz 3x3 de unos
print(lista_unos)

lista_identidad = np.eye(3)           # crea una matriz identidad 3x3
print(lista_identidad)

otra_lista = np.linspace(0, 30, 8)    # Array de 8 números, de 0 a 30 ambos incluidos
print(otra_lista)

#numeros = np.arange(10)               # Array de numeros (floats) de 0 a 9
# np.arange(4.)                       # Rango 0 a 4 decimal
# np.arange(-3, 3)                    # Rango de -3 a 2 
numeros = np.arange(0, 20, 2.5)                 # Rango de 0 a 20 cada 5 números
print(numeros)

# arreglo llenado de forma rapida. IMPORTANTE no con ceros
emptarray = np.empty((4,4))
print(emptarray)

Notar que si creamos un array con `np.arange()` usando un número entero, el array que se creará será de enteros. Es posible cambiar todo el array a otro tipo de dato (como a `float`) usando el método `astype()`, notar que se usa `dtype` para saber el tipo:

In [ ]:
print(numeros.dtype)


numeros = numeros.astype('int')  # para cambiar a float, notar que hay q volver a asignarle el valor
                                # puesto que astype crea una copia

print(numeros.dtype)

In [ ]:
# alternativa
test = np.array([1, 2.-1j, 3], dtype=complex)

print(test.dtype)

Nota: para conocer más detalles sobre los distintos tipos disponibles para los elementos de array, podemos echar un vistazo a la [página](https://numpy.org/doc/stable/reference/arrays.dtypes.html) de la documentación oficial asociada al tema.

## Ejercicios:
- importar NumPy con Alias
- Crear un arreglo 1D de 10 elementos mediante una lista
- Crear una matriz 5x5 de unos
- Crear una lista de ceros
- Convertir esa lista de ceros a complejos

### Indexación

Los arrays se indexan prácticamente igual que las listas y las cadenas de texto; aquí hay algunos ejemplos:

In [ ]:
numeros = np.arange(10)
print(numeros)

In [ ]:
print(numeros[3:8])           # Elementos desde el tercero al septimo

print(numeros[:4])            # Elementos desde el primero al cuarto

print(numeros[5:])            # Elementos desde el quinto al final

print(numeros[-3])            # El antepenúltimo elemento (devuelve un elemento, no un array)

print(numeros[:])             # Todo el array, equivalente a print(numeros)

print(numeros[2:8:2])         # Elementos del segundo al septimo, pero saltando de dos en dos

Hasta ahora es muy equivalente a las listas ¿cierto?

### Operaciones con arrays

Los arrays permiten hacer operaciones aritméticas básicas entre ellos en la forma que uno esperaría que se hicieran, es decir, haciéndolo elemento a elemento; para ello ambos arrays **deben tener siempre la misma longitud,** por ejemplo:

In [ ]:
enteros = np.arange(6)
x = np.array([5.6, 7.3, 7.7, 2.3, 4.2, 9.2])

print(enteros)
#print()
#print(x)
#print()

print(x+enteros)
print()

print(x*enteros)
print()

print(x/enteros)

Como podemos ver las operaciones se hacen elemento a elemento, por lo que ambas deben tener la misma forma (`shape()`). Fíjense que en la división el resultado del primer elemento es **indefinido/infinito (Inf)** debido a la división por cero.

¿qué sucede en Python cuando intentamos dividir un número por cero?

In [ ]:
1 / 0

Python arroja una excepción si encuentra una situación de este tipo, deteniendo por completo el proceso de la que forme parte. Algo que no ocurre con los array, para este caso recibimos un **warning** en la consola, pero el proceso continúa.

In [11]:
x = np.array([ 1,  0,  1, 16], dtype=int)
x/0

/var/folders/m_/bkm6rtjj0f104l91yr9n6t2c0000gn/T/ipykernel_56394/1715192346.py:2: RuntimeWarning: divide by zero encountered in divide
  x/0
/var/folders/m_/bkm6rtjj0f104l91yr9n6t2c0000gn/T/ipykernel_56394/1715192346.py:2: RuntimeWarning: invalid value encountered in divide
  x/0


array([inf, nan, inf, inf])

Notar que en los casos en que ocurre una indeterminación:
-  0/0
- raices cuadráticas negativas

NumPy devuelve el valor `nan`.


Notemos algo curioso

In [ ]:
# ejemplo 1
f = [np.nan, np.nan, np.inf, 1, 1.5]

f_l = []
for i in f:
    if i==i:
        f_l.append(i)
print(f_l)

In [ ]:
# ejemplo 2

np.nan == np.nan

Este resultado es bastante lógico. Si tenemos una entidad indefinida, difícil será que podamos comparar si es igual a otra entidad indefinida. No obstante, esta filosofía invalida la búsqueda de valores perdidos por la clásica vía de comparación con **nan**. En NumPy, para comprobar la existencia de dichos valores y que han sido codificados como **nan**, tendremos que emplear funciones del tipo `isnan()`.

In [ ]:
# ejemplo
np.isnan(x/0)

Finalmente, como tanto los **inf** como los **nan** se codifican de manera distinta a los números enteros, no vamos a poder tener en un array de enteros ciertos elementos declarados como **nan**.

In [ ]:
np.array([1, 2, np.nan], dtype='int8')

In [ ]:
# No obstante, con otros tipos de datos, esta situación no se da.
np.array([1, 2, np.nan], dtype='float32')

A modo de resumen, recuerden que con los arreglos las operaciones se realizan término a término

In [ ]:
a = np.arange(1,5)
print(a)
a**2

### Operaciones en arrays de 2D

Todo lo que hemos visto aplica también a los arrays de dos dimensiones:

In [12]:
# ejemplo
arr_5 = np.array([[1,2],[3,4]])
arr_6 = np.array([[5,6],[7,8]])

print(arr_5)
print()
print(arr_6)

arr_5 * arr_6

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


array([[ 5, 12],
       [21, 32]])

In [13]:
# ejemplo
a = np.arange(12)
b = a.reshape(3, 4)
print(b)
print()
print(b.ndim, a.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2 1


### Accediendo a los elementos

Es posible que, en este preciso instante, estemos tentados a denominar la primera dimensión del array b como filas y la segunda como columnas, por su similaridad con las tablas de datos con las que estamos acostumbrados a lidiar. No obstante, debemos ser cautos con esta nomenclatura

In [14]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
# ejemplos
b[2:, :2]  # fila [2,:), elementos [0, 2), recordar que empieza en 0

array([[8, 9]])

In [ ]:
# ¿qué retorna?
b[1:3, -1:]

In [ ]:
b[1:3, -1]  # notar que el resultado no conserva la estructura

In [18]:
b.shape, (b[1:3, -1]).shape

((3, 4), (2,))

Dependiendo de si acto seguido vamos a utilizar el anterior resultado para llevar a cabo algún tipo de cálculo matemático, este detalle puede resultar de vital relevancia.

Si estamos interesados en que el resultado de la extracción **conserve el número de dimensiones del objeto original**, en todas y cada una de las dimensiones hemos de emplear estrategias de tipo `slice`.

In [21]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
# ejemplos 1
b[:1, :1], b[:1, 0]

(array([[0]]), array([0]))

In [25]:
# ejemplo 2
b[1].shape, b[[1]].shape, b[1:2, :].shape

((4,), (1, 4), (1, 4))

¿Notan algo diferente?   El doble corchete

La primera estrategia de acceso a los elementos de un array empleando es **fancy indexing**. Se hace uso del tipo get donde proporcionaremos una lista ([]) que contenga los índices de los elementos que deseamos extraer. Ilustremos la manera de proceder mediante algunos ejemplos.

In [32]:
# ejemplos 
a = np.arange(15).reshape(3, 5)

print(a)
print()
print(a[[0, 1, 0]])  # filas 0, 1, 0. Noten como puedo repetir

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]]


In [31]:
a[0][[1, 3]]  # fila 0, elementos 1, 3

array([1, 3])

### Uniendo array

Varios arrays se pueden unir con el método `np.concatenate()`, que también se puede usar para añadir elementos nuevos:

In [ ]:
# ejemplos
arr_5 = np.array([[1,2],[3,4]])
arr_6 = np.array([[5,6],[7,8]])

print(arr_5)
print()
print(arr_6)
print()

a = np.concatenate((arr_5, arr_6))

print(a)

In [ ]:
arr_5 = np.array([1,2, 3,4])
arr_6 = np.array([5,6,7,8])

np.concatenate((arr_5, arr_6))

Para añadir elementos, numpy tiene las funciones `insert()` y `append()`, que funcionan de manera similar a sus equivalentes en listas:

In [ ]:
z = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(z)
# Añadimos el elemento 100 al array z, al final
z = np.append(z, 100)  # notar que como importamos todo el paquete no es necesario poner np.append

print(z)

# Añadimos el elemento 200 al array z, en el tercer puesto (índice 2)
b = np.insert(z, 2, 200)  # notar que como importamos todo el paquete no es necesario poner np.insert
print(b)

IMPORTANTE;

Como se ve, a diferencia de las listas (recordar que en la lista es `nombre.append(elemento)`, el **primer parámetro es el array y luego el elemento que se quiere añadir**.

- Estos métodos devuelven una copia del array sin modificar el original como hacen los métodos de listas correspondientes. 

- Si en lugar de un elemento a insertar se da una lista u otro array. Entonces se añade todos los elementos de la lista (a append() habría que dar también una lista de posiciones, como segundo parámetro).


### Operaciones aritméticas 
Además de las operaciones aritméticas básicas, los arrays de numpy tienen métodos o funciones específicas para ellas. Algunas de ellas son las siguientes:

In [ ]:
print(z.max())   # Valor máximo de los elementos del array

print(z.min())   # Valor mínimo de los elementos del array

print(z.mean())  # Valor medio de los elementos del array

print(z.std())   # Desviación típica de los elementos del array

print(z.sum())   # Suma de todos los elementos del array

print(np.median(z)) # Mediana de los elementos del array   se debe usar np.median si se importa numpy de la otra forma

OTRAS OPERACIONES

In [ ]:
b=np.array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

b.ndim

In [ ]:
# aplanando el arreglo
b.flatten()

In [ ]:
# operaciones por fila y columna
np.sum(b, axis=0) # reducción de la primera dimensión (suma por "columnas")

In [ ]:
np.sum(b, axis=1) # reducción de la segunda dimensión (suma por "filas")

## Ejercicios 

1. Crear un arreglo de 20 elementos
2. Convertirlo a un arreglo 2D
3. Calcular el min, max por filas y columnas
4. Calcular la media por filas
5. Añadir en cada fial un 10
6. Usando índices imprimir los ultimos 3 elementos del cada fila conservando la estructura
7. Con el arreglo del resultado anterior crear uno 1D

Una gran utilidad de los arrays es la posibilidad de usarlos con datos booleanos (True o False) y operar entre ellos o incluso usarlos con arrays con números. Veamos algunos ejemplos:

In [2]:
A = np.array([True, False, True])
B = np.array([False, False, True])

A*B

array([False, False,  True])

In [3]:
C = np.array([1, 2, 3])

A*C  #  los elementos que fueron multiplicados por False iguales a cero.

array([1, 0, 3])

In [ ]:
B*C  #  los elementos que fueron multiplicados por False iguales a cero.

En este ejemplo vemos cómo al multiplicar dos arrays booleanos es resultado es otro array booleano con el resultado que corresponda, pero al multiplicar los arrays booleanos con arrays numéricos, el resultado es un array numérico con los mismos elementos, pero con los elementos que fueron multiplicados por False iguales a cero.

Tambíén es posible usar los arrays como índices de otro array y como índices se pueden usar arrays numéricos o booleanos. El resultado será en este caso un array con los elementos que se indique en el array de índices numérico o los elementos correspondientes a True en caso de usar un array de índices booleano. Veámoslo con un ejemplo:

In [ ]:
# Array con enteros de 0 a 9
mi_array = np.arange(0, 100, 10)  #  np.arange

# Array de índices numericos con numeros de 0-9 de 2 en 2
indices1 = np.arange(0, 10, 2)

# Array de índices booleanos
indices2 = np.array([False, True, True, False, False, True, False, False, True, True])  # np.array

print(indices1)
print()
print(mi_array)
print()
print(mi_array[indices1])
print()
print(mi_array[indices2]) # notar que escoje los que son True

### array y booleanos

También es muy sencillo y más práctico crear arrays booleanos usando operadores lógicos y luego usalos como índices, por ejemplo:

In [4]:
mi_array = np.arange(0, 100, 10)

mi_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
# Creamos un array usando un operador booleano
mayores50 = mi_array > 50  # notar que compara cada elemento del arreglo con 50 y guarda sus comparaciones

print(mayores50)

# Lo utilizamos como índices para seleccionar los que cumplen esa condición
print(mi_array[mayores50])

[False False False False False False  True  True  True  True]
[60 70 80 90]


In [ ]:
# comparemos

mayores50 = []
for i in mi_array:
    if i>50:
        mayores50.append(i)
        
mayores50   

¡¡Genial no!!


Una de las mejores utilidades de numpy es trabajar con índices y máscaras de datos para limitar o seleccionar parte de los datos. Supongamos que tenemos un array de datos, pero que solo nos interesa los positivos, que queremos manipular después. Hay varias formas de seleccionarlos definiendo un array máscara con la condición que nos interesa:

In [6]:
datos = np.array([3, 7, -2, 6, 7, -8, 11, -1, -2, 8])

print(datos)

mask = datos >= 0

print(mask)

mask2 = datos*mask
print(mask2)

# no es lo mismo
print(datos[mask])

type(mask2)

[ 3  7 -2  6  7 -8 11 -1 -2  8]
[ True  True False  True  True False  True False False  True]
[ 3  7  0  6  7  0 11  0  0  8]
[ 3  7  6  7 11  8]


numpy.ndarray

- Usando un array mask de booleanos, podemos operar con el el array de datos, cuando un valor se multiplica por True es equivalente a multiplicarse por 1 y si es con False, a multiplicarse por 0. Por eso el resultado es un array del mismo tamaño, pero los elementos que no cumplen la condición se hacen 0.

- Si por el contrario usarmos usamos mask como un array de índices, el resultado es un array con los elementos cuyo índice corresponda con True, ignorando los de índice False. Usaremos uno u otro según lo que queramos hacer, el truco consiste es crear de manera correcta la máscara de datos.

Veamos el caso de un array 2D con dos columnas, pero queremos limitar todos los datos en criterios en las dos columnas. Primero creamos una máscara como producto de las dos condiciones, y luego la usamos como array de índices en el array original:

In [7]:
from numpy import random

In [22]:
datos2

array([[ -9,   0],
       [  8,   7],
       [ 14,   1],
       [  5,   1],
       [ 17, -10],
       [ 13,  -6],
       [ -2,   0],
       [  0,   2],
       [  1,  10],
       [  1,   5]])

In [28]:
np.random.seed(seed=123456)

datos2 = np.random.randint(-10, 20, (10, 2)) 
temp1 = datos2[:, 1]
temp2 = datos2[:, 0]
ind1 = temp1 > 3
ind2 = temp2%2 == 0
ind = ind1 * ind2
datos2[ind]

# mayor 3 segunda columna y multiplo de 2 el elemento de la primera

array([[8, 7]])

In [ ]:
datos2 = np.random.randint(-10, 20, (10, 2)) 
temp1 = datos2[:, 1]
temp2 = datos2[:, 0]
ind1 = temp1 > 3
ind2 = temp2%2 == 0
ind = ind1 * ind2
datos2[ind]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [18]:
temp=datos2>3
print(datos2[temp])

[ 8  7 14  5 17 13 10  5]


In [15]:
temp

array([[False, False],
       [ True,  True],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False, False],
       [False, False],
       [False,  True],
       [False,  True]])

In [ ]:
from numpy import random

np.random.seed(seed=123456)

datos2 = np.random.randint(-10, 20, (10, 2))  # crea 10 números aleatorios enteros entre [-10,20), para 2 columnas

print('arreglo de dos columnas \n', datos2)

# Solo queremos de los datos los que cumplan de la columna 0 que sean mayores 0
# pero en esa posición menores que 10 en la columna 1

condicion1 = datos2[:,0] > 0
condicion2 = datos2[:,1] < 10

print(condicion1)
print(condicion2)

# notar que al multiplicar las condiciones quedan las que son true true o false false
mask_col0 = condicion1*condicion2  
#mask_col0 = condicion1+condicion2 
mask_col1 = np.array([not(i) for i in (condicion1*condicion2)])
mask_col3 = mask_col0#*mask_col1
print(mask_col0)
#print(mask_col1)
#print(mask_col3)

# aplicando las condiciones
datos2[mask_col0]
#print(datos2[condicion1])
#print()
#datos2[condicion2]

Como se ve, el resultado en un array de dos columna, donde en la primera columna son todos positivos y en la segunda menores que +10. ¿Y si queremos que al menos se cumpla una condición? Simplemente tenermos que sumar las dos máscaras (las de cada columna) en lugar de multiplicarla, básicamente es como multiplicar o sumar unos o ceros (True o False).

## Ejercicio

Crear una matriz 4x4,

    a) extraer todos los elementos mayores que cero,
    b) extraer las filas que cumplan ser su primer elemento mayor que 1 y el segundo menor que 2,
    c) extraer las filas que cumplan que su primer elemento es mayor que 1 o su segundo elemento es menor que 2. Pero ambos no no pueden ser cierto.

### Retomando los índices

Igualmente podemos modificar un array bidimensional usando sus índices:

In [ ]:
lista = [[10,20,30, 4, 5,6,7,8,9, 0],[9, 99, 999, 8,9,0,4,2,7, 8],[9, 99, 999, 8,9,0,4,2,7, 8]]
arr0 =  np.array(lista)

print(arr0)

In [ ]:
arr0[:, 6] = 1
#arr0[-1, :] = 0
#arr0[1, 3:6] = 5
#arr0[1, -3] = 10
#arr0[-1, -1] = 10
#arr0[-1, -3:] = 1
#arr0[-1][[1, -2, -1]]=0
arr0[1, 1:4] = 5
print(arr0)

### Cambiando el tamaño de arrays

Hemos visto que es fácil quitar y poner elementos nuevos en un array unidimensional. Pero con dos o más dimensiones es algo más complicado porque estamos limitados a la estructura y número de elementos del array. Podemos cambiar la forma (shape) de un array a otra que tenga el mismo número de elementos fácilmente usado `reshape()`:

In [ ]:
numeros = np.arange(100)  # Array unidimensional de 100 numeros
numeros

In [ ]:
numeros_3D = numeros.reshape((5, 10, 2))  # creamos una arreglo de 5 x 10 x 2 .. notar que da 100 el producto
numeros_3D

In [ ]:
numeros = arange(10000)  # Array unidimensional de 10 000 numeros

numeros_2D = numeros.reshape((100, 100))  # creamos un arreglo 2D de 100 x 100

numeros_3D = numeros.reshape((100, 10, 10))  # creamos una arreglo de 100 x 10 x 10

print(numeros.shape)

print(numeros_2D.shape)

print(numeros_3D.shape)

### Arrays estructurados

Aunque los arrays pueden contener cualquier tipo de dato, los arrays normales sólo pueden ser de un único tipo. Para esto extiste una variante de arrays para contenidos complejos o estructurados, llamado **structured arrays**, que permiten tratar arrays por estructuras o por campos de estruturas. Además de poder contener distintos tipos de datos, facilitan el acceso por columnas. Vemos un ejemplo con un array con distintos tipos de datos:

In [ ]:
# ejemplo
galaxies = np.zeros(5, dtype = {'names': ('name', 'order', 'type', 'magnitude'),
                          'formats': ('U16', 'i4', 'U10', 'f8')})  # np.zeros


galaxies

In [ ]:
# ejemplo 
# Array estucturado de 5 elementos, vacio
galaxies = np.zeros(5, dtype = {'names': ('name', 'order', 'type', 'magnitude'),
                          'formats': ('U16', 'i4', 'U10', 'f8')})  # np.zeros

# Listas de datos para contruir el array estructurado
names = ["M 81", "NGC 253", "M 51", "NGC 4676", "M 106"]
types = ["SA(s)b", "SAB(s)c", "Sc", "Irr", "SAB(s)bc"]
magnitudes = [6.93, 7.1, 8.4, 14.7, 9.1]
order = list(range(5))

# Añadimos valores a los campos (columnas)
galaxies['name'] = names
galaxies['type'] = types
galaxies['magnitude'] = magnitudes
galaxies['order'] = order

print(galaxies)

Se trata de un array con cinco entradas (o records) y cada una de ellas posee cuatro campos de distinto tipo, indicados con la propiedad dtype. En este caso son un string unicode de:

- longitud máxima 16 (U16), 
- un entero 4 bytes (i.e. 32 bit) (i4), 
- string unicode de longitud máxima 16 (U16) y 
- un float de 4 bytes (i.e. 64 bit).

El dtype de numpy describe cómo interpretar cada elemento en bytes de bloques de memoria fijos. No sólo se trata de si son float, int, etc., el dtype describe lo siguiente:

- Tipo de dato (int, float, objeto Python, etc.)
- Tamaño del dato (cuantos bytes puede ocupar)
- Orden de bytes de datos (little-endian o big-endian)
- Si son datos estructurado (por ejemplo mezcla de tipos de dato), también:

    - Nombre de los campos
    - Tipo de dato de cada campo
    - Qué parte del bloque de memoria ocupa cada campo
    - Si en dato es un sub-array, su forma y tipo de dato

De manera resumida, para definir el tipo de cada elemento podemos usar una de las siguientes cadenas:

#### b1, i1, i2, i4, i8, u1, u2, u4, u8, f2, f4, f8, c8, c16, a<n>

que representan, respectivamente, 
    
    - bytes, 
    - ints, 
    - unsigned ints, 
    - floats, 
    - complex y 
    - strings de longitud fija. 
    
También se pueden usar los tipos de datos estándar de Python equivalentes (int, float, etc.)

COMENTARIOS: Uno puede computar la cantidad de bytes necesarios para almacenar un string usando la siguiente igualdad:


`Total (in bytes) = ((Números de bits por caracter)*(Numero de caracteres))/8`

Por ejemplo, el formato ASCII necesita $8$ bits para encodar cada caracter, por tanto una string como: ‘Hello World’ ocuparía $11$ bytes.  El formato `Unicode (UTF-16)`, necesita 16 bits por caracter, lo que conllevaría a ocupar $22$ bytes.


Teniendo un array estructurado como el anterior, podemos ver cada elemento haciendo el indexado habitual y también por campos (columnas):

In [ ]:
#print(galaxies)

# Columna 'name' del array
#print(galaxies['magnitude'])

# Primer elemento del array, con todos los campos (columnas)
#print(galaxies[0][0])

# Nombres de galaxias más brillantes que magnitud 9

indx = galaxies['magnitude'] < 9  # podemos crear un booleano y usarlo como índice
print(indx)
galaxies[indx]['name']

### Lectura y escritura de datos con numpy

numpy posee algunos métodos de lectura de ficheros de texto que nos pueden facilitar la vida si son relativamente sencillos. En más básico es 
- `np.loadtxt()`; 

si todos las columnas del fichero son numéricas, basta con indicar el delimitador de columnas si es distinto de espacios:

In [41]:
test2 = np.loadtxt('data/datos.txt', comments='#', delimiter='\t', unpack=False)  # Modificar: usecols=1 , comments='!', delimiter=';'
tiempo0 = test2[:, 0]  # tiempo, la primera columna
masa0 = test2[:, 1]  # masa, la segunda columna
print(test2)
print(tiempo0)

[[ 0.       -0.008936]
 [ 0.01     -0.008936]
 [ 0.02     -0.008935]
 [ 0.03     -0.008933]
 [ 0.04     -0.00893 ]
 [ 0.05     -0.008927]
 [ 0.06     -0.008923]
 [ 0.07     -0.008918]
 [ 0.08     -0.008912]
 [ 0.09     -0.008906]
 [ 0.1      -0.008899]
 [ 0.11     -0.008891]
 [ 0.12     -0.008882]
 [ 0.13     -0.008873]]
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13]


Si hay más de una columna como en este ejemplo, `np.loadtxt()` devuelve un array bidimiensional en el que primera dimensión o eje son las filas y el segundo las columnas. Quizás sea más práctico poner la columnas por separado, para lo que podemos hacer:

In [ ]:
tiempo1, masa1 = np.loadtxt('data/datos.txt', unpack=False)  # o una variable

Ahora al leer añadimos el parámetro `unpack=True`, `np.loadtxt()` lo que desempaqueta por columnas en lugar de por filas (como si invirtiera el array), perminiéndonos desempaquetar en variables las columnas, que ahora están en el eje 0:

Si el fichero a leer tiene distintos tipos datos (string y float), hay que indicar con el parámetro dtype la lista de tipos de dato que tienen las columnas que queremos leer. En este caso es más práctico usar el método
- `np.genfromtxt()`, 

que similar a`loadtxt()` pero más flexible para leer columnas de distinto tipo. Si usamos `np.genfromtxt()` con el parámetro dtype, que puede ser una lista con tuplas nombre-tipo, podemos indicar el nombre de la columna y el tipo dato que contiene, creando un array estructurado como vimos antes:

In [17]:
dtypes = [('tiempo', 'float'), ('masa', 'float'), ('letras', 'S10')]
data = np.genfromtxt("data/test2.dat", comments='!', delimiter=";", dtype=dtypes)  # dtype=None

#data
data['masa'], data['tiempo'], data['letras']

(array([-0.00893639, -0.008936  , -0.00893487, -0.00893297, -0.00893031,
        -0.0089269 , -0.00892274, -0.00891781, -0.00891214, -0.00890571,
        -0.00889853, -0.00889061, -0.00888194, -0.00887252]),
 array([1.0000000e-08, 1.0000010e-02, 2.0000010e-02, 3.0000010e-02,
        4.0000010e-02, 5.0000010e-02, 6.0000010e-02, 7.0000010e-02,
        8.0000010e-02, 9.0000010e-02, 1.0000001e-01, 1.1000001e-01,
        1.2000001e-01, 1.3000001e-01]),
 array([b' adios', b' hola', b' c', b' d', b' e', b' f', b' g', b' h',
        b' i', b' j', b' k', b' l', b' m', b' n'], dtype='|S10'))

En este caso ya no hay que usar el desempaquetado, porque tenemos un array estructurado con columnas con nombre data['tiempo'] y data['masa'].

De manera similar, podemos usar 
- `np.savetxt()` 

para guardar un fichero de datos por columnas:

In [ ]:
# Guardamos un array datos en un fichero de texto, con los campos
# delimitados por tabulador (\t) en formato float con dos decimales
# y le damos una cabecera
np.savetxt('datos.txt', data, delimiter='\t', fmt='%.6f', header="tiempo\t masa")

En este ejemplo delimitamos las columnas por tabuladores (\t), escribimos los números como floats con dos decimales (%.2f, por defecto es notación científica) y añadimos un string que hace de cabecera.

# Cálculo matricial con numpy

numpy incluye algunas funciones para álgebra y cálculo matricial, en el que es clave el tipo de dato matrix. Es similar al array, pero opera como una matrix y tiene método propios de las matrices.

In [ ]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[1,2,0], [4,5,6], [7,8,9]])
Am = np.mat(A)
Bm = np.mat(B)

In [ ]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

Am = np.mat(A)  # Convertimos array a matriz
print(Am)
print()
print(A*A)  
print()
print(Am*Am)  # Aquí hace producto matricial, no elemento a elemento como con arrays

print()
print(np.dot(A,A))

In [ ]:
print(Am.T)  # Matriz traspuesta
print()
print(Am.diagonal())
print()
print(np.linalg.det(Am)) # Determinante
print()
print(np.linalg.eigvals(Am))  # Autovalores

In [ ]:
?np.linalg.eigvals

### Proxima clase: Matplotlib